heat_template_version: 2014-10-16

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: ubunut-test
      flavor: m1.medium
      key_name: vinod-key
      user_data_format: SOFTWARE_CONFIG
      networks:
        - network: mgmt1
outputs:
  server_id:
    value: {get_resource: server}
  server_ip:
    value: {get_attr: [server, networks, mgmt1, 0]}
