
heat_template_version: 2014-10-16
description: A simple auto scaling group.
resources:
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: net04_ext

  inst1:
    type: OS::Nova::Server
    properties:
      flavor: m1.medium
      image: ubunut-test
      networks:
        - network: mgmt1
      user_data_format: HEAT_CFNTOOLS
      user_data:
         #!/bin/bash
         sudo apt-get update
         echo "Hello world" > ~/test
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        get_file: /Users/lab3/test.sh
  
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: inst1 }
