heat_template_version: 2014-10-16
description: A simple auto scaling group.
resources:
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: net04_ext

  inst1:
    type: OS::Nova::Server
    properties:
      flavor: m1.medium
      image: ubunut-test
      key_name: vinod
      networks:
        - network: SDN-NFV-Demo-Titus-PN10
      user_data: 
        str_replace: 
          template: |
            #!/bin/bash -v
            - echo "VINOD" > test.txt
        
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: inst1 }
