heat_template_version: 2014-10-16
description: A simple server.
resources:
  server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - device_name: vda
          delete_on_termination: true
          volume_id: { get_resource: volume }
      flavor: m1.amphora
      networks:
        - network: lb-mgmt-net
      user_data_format: RAW
  volume:
    type: OS::Cinder::Volume
    properties:
      image: 'ub'
      size: 4

